### ISSUE TITLE
Redirect from old website

### ISSUE THREAD

**Issue by cifkao** [mip-frontiers/mip-frontiers.github.io#6]
The old website at upf.edu is still higher in Google results than the new one. Can we set up a redirect?

If a [HTTP redirect](https://css-tricks.com/snippets/htaccess/301-redirects/) is not possible, we can at least do this:

```html
<head>
  <link rel="canonical" href="https://mip-frontiers.eu">
  <meta http-equiv="refresh" content="0; url=https://mip-frontiers.eu" />
</head>
```

**Comment by philtgun** [comment]
Will add the HTML redirect because UPF doesn't allow redirects to external websites (we tried to do it at the launch).

**Comment by philtgun** [comment]
Update: after several discussions in UPF, and redirect not being possible (even HTML), there were 2 options:
1. Delete the UPF website, thus having .eu higher in gsearch, but **it is bad** due to historic URL that have been mentioned on documents result in 404
2. Retain the website, add directives for it to be stopped from being indexed (already done), and use .eu more and maybe add SEO

Thus we decided to go with the second one. 2nd and 3rd results in gsearch (blog and institutions) are returning 404, so they should disappear from gsearch soon.

The issue now is the gsearch ranking. Thus we can either keep this issue to work on SEO, or close it and open a new one.

**Comment by cifkao** [comment]
Hmm... Then I guess it's not even possible to change the "canonical" tag at the UPF website (which currently points to upf.edu)?

Also, the [QMUL website](http://mip-frontiers.eecs.qmul.ac.uk/) (which is above mip-frontiers.eu in gsearch) still redirects to the UPF website. It should be possible to change that and also add the "canonical" tag, right? Then it should disappear from the results once it gets reindexed.

**Comment by philtgun** [comment]
Nope, it is difficult to do any changes, that's why we migrated :)
Yes, we need to ask somebody at QMUL who can take care of the updating the link.
Also .eu is above the qmul link for me
![image](https://user-images.githubusercontent.com/1110902/61627208-7aa57a80-ac7f-11e9-8748-18af67126cff.png)

**Comment by cifkao** [comment]
This is what my search results look like in incognito mode and after opting out of personalized results:

![image](https://user-images.githubusercontent.com/8046580/61628983-002b2980-ac84-11e9-9993-89ca9f4da015.png)

**Comment by philtgun** [comment]
I guess this issue can be closed now
![image](https://user-images.githubusercontent.com/1110902/92758158-b7a26400-f38e-11ea-857e-ef1138299d68.png)
